(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.텍스트2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 레이어_1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#055DB0","#0D957C"],[0,1],-351.5,26.5,-96,-273).s().p("AgHB5IAAjxIAaAAIAADxgAlPB5IAAhVIhnAAIAAgXIDwAAIAAAXIhtAAIAABVgAqiB5IAAhXIhqAAIAAgXIDxAAIAAAXIhsAAIAABXgANJBzIAAhJIAcAAIAAAyICWAAIAAAXgABJBzIAAhJIAcAAIAAAyICfAAIAAAXgAKZBJQgSgbAAguQAAgvASgbQATgcAiAAQAiAAATAcQATAbAAAvQAAAtgTAcQgTAcgiAAQgiAAgTgcgAKug5QgLAWAAAjQAAAiALAWQAMAXAUAAQAVAAAMgXQAKgWAAgiQAAgkgLgVQgLgXgVAAQgUAAgMAXgAH4BJQgSgbAAguQAAgvASgbQATgcAiAAQAiAAATAcQATAbAAAvQAAAtgTAcQgTAcgiAAQgiAAgTgcgAINg5QgLAWAAAjQAAAiALAWQAMAXAUAAQAVAAAMgXQAKgWAAgiQAAgkgLgVQgLgXgVAAQgUAAgMAXgAGvBjIAAiOIgrAAIAAgUQAUgBAOgJQANgKABgRIATAAIAADHgAv6BaIAAgXIBqAAIAAg2IhJAAIAAhvICuAAIAABvIhJAAIAAA2IBqAAIAAAXgAu+gJIB3AAIAAhCIh3AAgAivgYIBbAAIAAgxIhbAAIAAgYIB2AAIAABgIhaAAIAAAyIAyAAQAtgCAdgEIAAAXQgxAGgiAAIhFABgAPaA2IAAhSIhFAAIAAgWIBFAAIAAgWIhFAAIAAgWIBFAAIAAgaIAbAAIAACugAAqAUIAAgWIDxAAIAAAWgAMvhuIAbAAIAABrIAhAAQAygBAkgIIAAAWQgmAIgxABIg7AAgArsgSIAAhbICyAAIAAAXIiXAAIAAAtICaAAIAAAXgAmXgVIAAhdIAbAAIAABGICbAAIAAAXgABJggIAAhXIAcAAIAABAICaAAIAAAXg");
	this.shape.setTransform(0.025,0.025);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.텍스트2, new cjs.Rectangle(-101.9,-12,203.9,24.1), null);


(lib.텍스트1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 레이어_1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#055DB0","#0D957C"],[0,1],-351.6,57.9,-96.1,-241.6).s().p("AA0B5IAAg5Ig7AAIAAgYIA7AAIAAigIAcAAIAADxgAotB5IAAjwIAbAAIAADwgAlXB3IAAg9ICTAAIAAgTIiTAAIAAgVICyAAIAAA8IiTAAIAAATICaAAIAAAWgAvPB3IAAhPICtAAIAABPgAu0BgIB2AAIAAgiIh2AAgAM9BzIAAhIIAdAAIAAAyICaAAIAAAWgACGBzIAAhCIAcAAIAAAsICjAAIAAAWgAhJBzIAAhlIhCAAIAAgXIBuAAQAHggACgjIhnAAIAAgXICFAAQgEBCgHAXQAWAAAWgEIAAAVQgpAHgwAAIAABlgApfBvIAAhxIgaAAIAAgYIAaAAIAAhXIAaAAIAADggAHzBXQgSgPgDgXIAYAAQACANAMAKQAMALARAAQASAAAMgOQALgNAAgTQAAgVgKgMQgMgOgSAAQgaAAgNAQIgYAAIAQhmIBsAAIAAAWIhXAAIgIA0QATgLAYACQAWACAQAPQAWASAAAgQAAAfgWAUQgUARgaAAQgdAAgTgRgAKIBKQgTgcAAguQAAguATgbQATgcAjgBQAkAAATAcQATAcAAAuQAAAvgTAbQgTAcgkABQgjAAgTgdgAKdg4QgLAVAAAjQAAAjALAWQAMAWAVAAQAWAAAMgWQALgWAAgjQAAgjgLgWQgMgWgWAAQgVAAgMAXgArGBLQAZgdAOgjQAPglAAgnIgZAAIAAgWIA0AAQABBdg7BOgAr/A7QAXgXAOgjQANggABgiIgiAAIAAgWIA+AAQAAAqgQArQgQAsgZAagAPTA3IAAhTIhHAAIAAgVIBHAAIAAgWIhHAAIAAgWIBHAAIAAgbIAcAAIAACvgABmAcIAAgYIBtAAIAAgYQgngCgVgOQgUgNAAgVQAAgXAYgNQAZgPAuAAQAtAAAZAPQAYANAAAXQAAAVgUANQgVAOgnACIAAAYIBtAAIAAAYgACyhbQgRAIAAANQAAANARAIQASAJAeAAQAdAAASgJQARgIAAgMQAAgOgRgIQgSgJgdAAQgdAAgTAJgAs+AYIAAiQIAcAAIAAA+IAjAAIAAAWIgjAAIAAA8gAvWAOQgTgMAAgPQAAgQATgLQATgKAfAAQAeAAATAKQASALAAAQQAAAQgSALQgTALgfgBQgdABgUgLgAvBgbQgLAGAAAIQAAAJALAEQALAFASgBQARABALgFQAKgEAAgJQAAgIgKgGQgLgEgRAAQgSAAgLAEgAMihtIAcAAIAABrIAigBQAtAAAsgIIAAAWQgnAIgyABIg+AAgAjBAHIAAh/IAcAAIAAB/gAlngPQgVgRAAgYQAAgYAVgQQATgQAbAAQAbAAATAQQAVAQAAAYQAAAYgVARQgTAPgbAAQgbAAgTgPgAlUhOQgLAJAAAMQAAAOALAKQAMAJAPAAQAPAAAMgJQALgLAAgNQAAgMgLgKQgMgJgPAAQgPAAgMAKgAvzg9IAAgXICdAAIAAAXgAvOhjIAAgVIBSAAIAAAVg");
	this.shape.setTransform(0.025,0);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.텍스트1, new cjs.Rectangle(-101.2,-12.1,202.5,24.299999999999997), null);


// stage content:
(lib._50주년인트로 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [87];
	// timeline functions:
	this.frame_87 = function() {
		var _this = this;
		/*
		동영상 클립/비디오 중지
		지정한 동영상 클립 또는 비디오를 중지합니다.
		*/
		_this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(87).call(this.frame_87).wait(1));

	// Group_23_svg
	this.instance = new lib.텍스트1();
	this.instance.setTransform(527.15,289.7);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(59).to({_off:false},0).to({x:497.15,alpha:1},10).wait(19));

	// 레이어_3
	this.instance_1 = new lib.텍스트2();
	this.instance_1.setTransform(527.05,321.1);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(67).to({_off:false},0).to({x:497.05,alpha:1},10).wait(11));

	// Group_23_svg
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#055DB0","#0D957C"],[0,1],3.8,252.1,259.3,-47.3).s().p("AA+CzIgJgCQgYgFgNgBIgWgBQgOgBgJgBQgPgCgOgGQgjgVgVghQgJgNgHgRIgKgbIgKgTQgDgRgEgIIgEgFQAHgIgEgNQgBgFACgHIgCgEIgFgKQgCgGADgGQABgCgDgFIgBgEIgLAIIAAgDQgBgGABgCQAFgGgBgHQgBgEgEgIIgBgBIgKgRIgHgLQgLgTAGgVIAGgMIABAEQABAHABACQADACAGgFIADAAIAEADQAbAcAggDQAngDAcgSICVA8QAkAOASAMQAcARAMAXQANAXgCAeQgBAbgNAbQgPAggaAaQgZAZggAPIgZALIgFgBg");
	this.shape.setTransform(141.6855,95.4125);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["#055DB0","#0D957C"],[0,1],-2.6,251.7,252.9,-47.8).s().p("AAaC0IgkgHQgYgFgNgCIgXgBQgOAAgJgCQgPgCgOgFQgjgWgVggQgJgOgHgQIgKgbIgKgTQgDgRgEgIIgEgFQAHgJgEgMQgBgFACgIIgCgEIgFgJQgCgGADgHQABgCgDgEIgBgEIgLAIIAAgEQgBgGABgBQAFgGgBgHQgBgFgEgHIgBgCIgKgRIgHgKQgLgUAGgVIAGgMIABAEQABAIABABQADADAGgFIADAAIAEACQAbAcAggCQA0gFAggeIABgCQAXADAsACQBMAGBdAgQA2ATAYARQAoAdAIAoQALAzgwA6QgoAzg6AdQgfAPg0APQgHgEgPgBg");
	this.shape_1.setTransform(148.0672,95.8875);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["#055DB0","#0D957C"],[0,1],-15.6,253.5,239.9,-45.9).s().p("AhnDGIglgHQgYgFgNgBIgXgBQgOgBgJgBQgPgCgOgGQgjgVgVghQgJgNgHgRIgKgbIgKgTQgDgRgEgIIgEgFQAHgJgEgMQgBgFACgHIgCgEIgFgKQgCgGADgGQABgCgDgFIgBgEIgLAIIAAgDQgBgGABgCQAFgGgBgHQgBgEgEgIIgBgBIgKgRIgHgLQgLgTAGgVIAGgMIABAEQABAHABACQADACAGgFIADAAIAEADQAbAcAggDQA0gFAggeIAIgIIB/gYQAigGARgFQARAEAYACIAyAGQAUAEAiAKIA1APQAeAHA7AJQA1AKAgASQAUAMAjAfQAMAKAAAIQABAGgGAKQgjA5hKBAQhYBEgpAlIgDADIgkADIiiAIQgSABgMAIQgIgGgTgCg");
	this.shape_2.setTransform(161.0741,94.0125);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.lf(["#055DB0","#0D957C"],[0,1],-29.6,257.3,225.9,-42.2).s().p("AjzDsIglgHQgYgFgNgCIgXgBQgOAAgJgCQgPgCgOgFQgjgWgVggQgJgOgHgQIgKgbIgKgTQgDgRgEgIIgEgGQAHgJgEgMQgBgFACgIIgCgEIgFgJQgCgFADgHQABgCgDgEIgBgEIgLAIIAAgEQgBgGABgBQAFgGgBgHQgBgFgEgHIgBgCIgKgRIgHgKQgLgUAGgVIAGgMIABAEQABAIABABQADADAGgFIADAAIAEACQAbAcAggCQA0gFAggeIAIgJIB/gYQAmgHARgFQAXgHAngQIBVgjQA1gBBBgPIADABQDIAaAjAHQCDAbBSA8IiGCHIgzAyQgeAcgaASQguAhhIAeIh6AuIAFAAQgsAFgqADIijAJQgSAAgNAJQgHgHgTgBg");
	this.shape_3.setTransform(175.0971,90.2875);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.lf(["#055DB0","#0D957C"],[0,1],-44.6,260.8,210.9,-38.6).s().p("AmJEPIglgHQgYgFgNgBIgXgBQgOgBgJgBQgPgCgOgGQgjgWgVggQgJgNgHgRIgKgbIgKgTQgDgRgEgIIgEgFQAHgJgEgNQgBgFACgHIgCgEIgFgKQgCgGADgGQABgCgDgFIgBgEIgLAIIAAgDQgBgGABgCQAFgGgBgHQgBgDgEgIIgBgBIgKgRIgHgLQgLgTAGgVIAGgMIABAEQABAHABACQADACAGgFIADAAIAEADQAbAcAggDQA0gFAggeIAIgIIB/gYQAmgHARgGQAXgGAngRIBVgiQBRgCBpgfIAKgDIBAgSIAGgCQAZAGAngBQFThHDHBEIkBDmQhLBCgnAeQhBA0g8AeQhKAliYAoIgyANQgsAFgtAEIijAIQgSABgMAIQgIgGgTgCg");
	this.shape_4.setTransform(190.0721,86.7216);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.lf(["#055DB0","#0D957C"],[0,1],-51.8,262.5,203.7,-36.9).s().p("AnREgIglgHQgYgFgOgBIgWgBQgPgBgIgBQgPgCgOgGQgkgVgVghQgJgNgGgRIgLgbIgJgTQgEgRgEgIIgEgFQAIgJgEgNQgCgFADgHIgDgEIgFgKQgBgGADgGQAAgCgCgFIgCgEIgKAIIgBgDQgBgGABgCQAFgGgBgHQgBgEgEgIIAAgBIgLgQIgGgLQgMgTAGgVIAGgMIABAEQABAHACACQACACAGgFIAEAAIADADQAcAcAggDQAzgFAggeIAIgIIB/gYQAngHARgGQAXgGAngRIBUgiQBRgCBrgfIBdgbIB2giQB1ggBuAFIGEAOIgEAKIgIAUQgUAognAgQgKAJgSALIgRAKIgMALIgrAsIhyB1QhOBSh7A4Qh1A1ijAgQh6AYh2AJIijAIQgSABgNAIQgHgGgTgCg");
	this.shape_5.setTransform(197.3221,85.0158);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).wait(83));

	// 레이어_9
	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.lf(["#055DB0","#0D957C"],[0,1],-26.5,216.2,229,-83.2).s().p("AvxLqIgEgHIAAAAIAHAMIACADIAEAGIgJgOgAljh9QgngBgUgNQgUgNgUgqQgfg+gJglIgFgZIAigoQAIgJgEgNQgBgFACgHIgCgEIgFgKQgCgGADgGQABgCgDgFIgBgEIgLAIIAAgDQgBgGABgCQAFgGgBgHQgBgEgEgIIgBgBIgKgRIgHgLQgLgTAGgVIAGgMIABAEQABAHABACQADACAGgFIADAAIAEADQAbAcAggDQA0gFAggeQAUgTAdgwIAHgMQAYgoAOgTQAfgoAxAAQAUAAAJANQABACAEABIABAAIACAUIADABIAHgNIAjAbQALAKAIAEQAXALAPAAQBXACB7gjIBegbIB2giQB2ggBtAFIGEAOIgDAKIgIAUQgVAogmAgQgLAJgSALIgQAKIgMALIgrAsIhyB2QhPBSh7A4Qh1A1ikAgQh5AYh3AJIiiAIQggACgQAaIgNAEQg8ASg+AAIgRAAg");
	this.shape_6.setTransform(171.9875,131.3408);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.lf(["#055DB0","#0D957C"],[0,1],-26.5,216.2,229,-83.2).s().p("AvxLqIgEgHIAAAAIAHAMIACADIAEAGIgJgOgAoqAnQgbgCgOgDQgXgFgOgMQgXgSgFgnQgDgSABg0IAAgTIDFjlQAIgJgEgNQgBgFACgHIgCgEIgFgKQgCgGADgGQABgCgDgFIgBgEIgLAIIAAgDQgBgGABgCQAFgGgBgHQgBgEgEgIIgBgBIgKgRIgHgLQgLgTAGgVIAGgMIABAEQABAHABACQADACAGgFIADAAIAEADQAbAcAggDQA0gFAggeQAUgTAdgwIAHgMQAYgoAOgTQAfgoAxAAQAUAAAJANQABACAEABIABAAIACAUIADABIAHgNIAjAbQALAKAIAEQAXALAPAAQBXACB7gjIBegbIB2giQB2ggBtAFIGEAOIgDAKIgIAUQgVAogmAgQgLAJgSALIgQAKIgMALIgrAsIhyB2QhPBSh7A4Qh1A1ikAgQh5AYh3AJIiiAIQgiACgQAcIglBAIAAAAIg5BiIgYAJQgxAQhBACIgNAAQgnAAhBgFg");
	this.shape_7.setTransform(171.9875,131.3408);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.lf(["#055DB0","#0D957C"],[0,1],-26.5,216.2,229,-83.2).s().p("AvxLqIgEgHIAAAAIAHAMIACADIAEAGIgJgOgAr5G7QgSAAgXgYQgpgtgHgjQgGgdAKguQAOhDAahCIARgrQAKgaAEgTQAFgYgCgUIgDADIAHgHIAAAAIEvlhQAIgJgEgNQgBgFACgHIgCgEIgFgKQgCgGADgGQABgCgDgFIgBgEIgLAIIAAgDQgBgGABgCQAFgGgBgHQgBgEgEgIIgBgBIgKgRIgHgLQgLgTAGgVIAGgMIABAEQABAHABACQADACAGgFIADAAIAEADQAbAcAggDQA0gFAggeQAUgTAdgwIAHgMQAYgoAOgTQAfgoAxAAQAUAAAJANQABACAEABIABAAIACAUIADABIAHgNIAjAbQALAKAIAEQAXALAPAAQBXACB7gjIBegbIB2giQB2ggBtAFIGEAOIgDAKIgIAUQgVAogmAgQgLAJgSALIgQAKIgMALIgrAsIhyB2QhPBSh7A4Qh1A1ikAgQh5AYh3AJIiiAIQgiACgQAcIglBAIAAAAQgzBWgYAtQggA4gVAxIAEgIIgHAFQgOANgIASIgCAFIgJALQgaASgYAhIgBABIgDAEIAAAAIgSAMQilBnhQA5QgYAQgOAAIAAAAg");
	this.shape_8.setTransform(171.9875,131.3408);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.lf(["#055DB0","#0D957C"],[0,1],-26.5,216.2,229,-83.2).s().p("AvxLqIgEgHIAAAAIAHAMIACADIAEAGIgJgOgAttI8QgVgCgSgOQgRgOgKgUQgQgegEg2QgHhbAPhaQAFgkAAgLIAAgFIHlozQAIgJgEgNQgBgFACgHIgCgEIgFgKQgCgGADgGQABgCgDgFIgBgEIgLAIIAAgDQgBgGABgCQAFgGgBgHQgBgEgEgIIgBgBIgKgRIgHgLQgLgTAGgVIAGgMIABAEQABAHABACQADACAGgFIADAAIAEADQAbAcAggDQA0gFAggeQAUgTAdgwIAHgMQAYgoAOgTQAfgoAxAAQAUAAAJANQABACAEABIABAAIACAUIADABIAHgNIAjAbQALAKAIAEQAXALAPAAQBXACB7gjIBegbIB2giQB2ggBtAFIGEAOIgDAKIgIAUQgVAogmAgQgLAJgSALIgQAKIgMALIgrAsIhyB2QhPBSh7A4Qh1A1ikAgQh5AYh3AJIiiAIQgiACgQAcIglBAIAAAAQgzBWgYAtQggA4gVAxIAEgIIgHAFQgOANgIASIgCAFIgJALQgaASgYAhQgSAXghAxQgsA7hQBAQgxAogsAaQgbAQg5AbQgWAKgMAEQgPAEgOAAIgGAAg");
	this.shape_9.setTransform(171.9875,131.3408);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.lf(["#055DB0","#0D957C"],[0,1],-23,216.2,232.5,-83.2).s().p("AwFJzIABAEQAWBAAlA7IADAGQgog/gXhGgAuLLAQgwgMgXgXQgHgHgNgRQgMgQgIgHQgHgGgIgEIgBAAIgBgEIAAgBQgfhvAuh9QAbhKBHhTIHso8QAIgJgEgNQgCgFADgHIgDgEIgFgKQgBgGADgGQAAgCgCgFIgCgEIgKAIIgBgDQgBgGABgCQAFgGgBgHQgBgEgEgIIAAgBIgLgRIgGgLQgMgTAGgVIAGgMIABAEQABAHACACQACACAGgFIAEAAIADADQAcAcAggDQAzgFAggeQAVgTAcgwIAIgMQAYgoAOgTQAfgoAwAAQAVAAAJANQABACADABIACAAIABAUIAEABIAHgNIAjAbQALAKAIAEQAXALANAAQBZACB7gjIBegbIB2giQB1ggBuAFIGEAOIgEAKIgIAUQgUAognAgQgKAJgSALIgRAKIgMALIgrAsIhyB2QhOBSh7A4Qh1A1ikAgQh6AYh2AJIiiAIQgiACgQAcIglBAIAAAAQgzBWgYAtQggA4gVAxIADgIIgGAFQgOANgJASIgCAFQgfAjgSBHIgPA9QgLAjgOAYQgHALgOATIgWAfQgOAVgVAwQgVAwgPAVQgaAmgpAaQgoAZgwAKQgiAIglAAQg2AAg9gQg");
	this.shape_10.setTransform(168.5348,131.3408);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.lf(["#055DB0","#0D957C"],[0,1],-23,210.2,232.5,-89.3).s().p("AsRM0IgZgDQgIgBgCgCQgFgEABgJQAAgCgEgGIgCgEIgEAAIgEATQgigKgagcIgBgFIAAgBIgCgMIgKAJIgEgEIgOgNQgCgEABgIQABgHAAgDQgBgFgFgEIgIATIgSgZQgyhLgYhVQgfhwAuh8QAbhKBHhUIHso7QAIgJgEgNQgCgFADgIIgDgEIgFgJQgBgGADgHQAAgCgCgEIgCgEIgKAIIgBgEQgBgGABgBQAFgGgBgHQgBgFgEgHIAAgCIgLgRIgGgKQgMgUAGgVIAGgMIABAEQABAIACABQACADAGgFIAEAAIADACQAcAcAggCQAzgFAggeQAVgUAcgwIAIgMQAYgoAOgSQAfgoAwAAQAVAAAJANQABABADABIACABIABATIAEABIAHgNIAjAbQALAKAIAEQAXALANAAQBZADB7gkIBegbIB2giQB1gfBuAFIGEAOIgEAKIgIATQgUAognAhQgKAIgSALIgRALIgMALIgrAsIhyB2QhOBSh7A3Qh1A1ikAhQh6AXh2AJIiiAJQgiABgQAdIglA/IAAABQgzBXgYAsQgzBagXBFIgFASIALgCQgGALgBAKQgCAQAIARQAIAPAOALQAOAMAeAMIAEAEQAUAXAGAMQAJAOAEAaQAGAegGASQgEANgMAOQgIAIgRAOQhDA4g1AwQg9A2gcAkIgOAJQgwAihjBMIhLA6QgZAEgXAAIgJAAg");
	this.shape_11.setTransform(168.5348,137.3715);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.lf(["#055DB0","#0D957C"],[0,1],-23,210.2,232.5,-89.3).s().p("AsRM0IgZgDQgIgBgCgCQgFgEABgJQAAgCgEgGIgCgEIgEAAIgEATQgigKgagcIgBgFIAAgBIgCgMIgKAJIgEgEIgOgNQgCgEABgIQABgHAAgDQgBgFgFgEIgIATIgSgZQgyhLgYhVQgfhwAuh8QAbhKBHhUIHso7QAIgJgEgNQgCgFADgIIgDgEIgFgJQgBgGADgHQAAgCgCgEIgCgEIgKAIIgBgEQgBgGABgBQAFgGgBgHQgBgFgEgHIAAgCIgLgRIgGgKQgMgUAGgVIAGgMIABAEQABAIACABQACADAGgFIAEAAIADACQAcAcAggCQAzgFAggeQAVgUAcgwIAIgMQAYgoAOgSQAfgoAwAAQAVAAAJANQABABADABIACABIABATIAEABIAHgNIAjAbQALAKAIAEQAXALANAAQBZADB7gkIBegbIB2giQB1gfBuAFIGEAOIgEAKIgIATQgUAognAhQgKAIgSALIgRALIgMALIgrAsIhyB2QhOBSh7A3Qh1A1ikAhQh6AXh2AJIiiAJQgiABgQAdIglA/IAAABQgzBXgYAsQgzBagXBFIgFASIAPgDIA7gRIABAAIBegcQAvAbBUgIQAQAEATACQAhAEA1gFIABAAIAzgFIBggKIgCAAIgTACIhCAHIAEADQAYARAmAHQALACA6AGIAWACIAEACQAeASA8AYIDxBgQgoAfg2AiIhjA4IgFADIAAAAIgBAAIgHACIgfAOIgBABIgFAAIl5A9QiwAzi7BdIhmA0IhxA6QhnAyhZAAIgIAAgAF+HHIADAAIgIAAIAFAAgAGCHHIgBAAIAEAAIgCAAIgBAAg");
	this.shape_12.setTransform(168.5348,137.3714);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.lf(["#055DB0","#0D957C"],[0,1],-23,210.2,232.5,-89.3).s().p("AsRM0IgZgDQgIgBgCgCQgFgEABgJQAAgCgEgGIgCgEIgEAAIgEATQgigKgagcIgBgFIAAgBIgCgMIgKAJIgEgEIgOgNQgCgEABgIQABgHAAgDQgBgFgFgEIgIATIgSgZQgyhLgYhVQgfhwAuh8QAbhKBHhUIHso7QAIgJgEgNQgCgFADgIIgDgEIgFgJQgBgGADgHQAAgCgCgEIgCgEIgKAIIgBgEQgBgGABgBQAFgGgBgHQgBgFgEgHIAAgCIgLgRIgGgKQgMgUAGgVIAGgMIABAEQABAIACABQACADAGgFIAEAAIADACQAcAcAggCQAzgFAggeQAVgUAcgwIAIgMQAYgoAOgSQAfgoAwAAQAVAAAJANQABABADABIACABIABATIAEABIAHgNIAjAbQALAKAIAEQAXALANAAQBZADB7gkIBegbIB2giQB1gfBuAFIGEAOIgEAKIgIATQgUAognAhQgKAIgSALIgRALIgMALIgrAsIhyB2QhOBSh7A3Qh1A1ikAhQh6AXh2AJIiiAJQgiABgQAdIglA/IAAABQgzBXgYAsQgzBagXBFIgFASIAPgDIA7gRIABAAQBfgcApgNQBAgVB6gWIABAAIAxgKQBzgWBuABQCUACCPBHQAfAPAtAYIABAAIAzAbQAIAFAAAJQgBALAGAHQAGAIAIAAIgGgPIACgCIABABIABAAIACACIAmAjIgOBBQgEAVgEAJQgFAQgKAKQgJALgUAKQg3Aeg9AKIhCAKQggAFgWAKIAAAAIgFgBIgfgFIgDAAQgpAAglAVIgBABIgFAAIl5A9QiwAzi7BdIhmA0IhxA6QhnAyhZAAIgIAAgAF+HHIAHAAIgMAAIAFAAg");
	this.shape_13.setTransform(168.5348,137.3714);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.lf(["#055DB0","#0D957C"],[0,1],-23,210.2,232.5,-89.3).s().p("AsRM0IgZgDQgIgBgCgCQgFgEABgJQAAgCgEgGIgCgEIgEAAIgEATQgigKgagcIgBgFIAAgBIgCgMIgKAJIgEgEIgOgNQgCgEABgIQABgHAAgDQgBgFgFgEIgIATIgSgZQgyhLgYhVQgfhwAuh8QAbhKBHhUIHso7QAIgJgEgNQgCgFADgIIgDgEIgFgJQgBgGADgHQAAgCgCgEIgCgEIgKAIIgBgEQgBgGABgBQAFgGgBgHQgBgFgEgHIAAgCIgLgRIgGgKQgMgUAGgVIAGgMIABAEQABAIACABQACADAGgFIAEAAIADACQAcAcAggCQAzgFAggeQAVgUAcgwIAIgMQAYgoAOgSQAfgoAwAAQAVAAAJANQABABADABIACABIABATIAEABIAHgNIAjAbQALAKAIAEQAXALANAAQBZADB7gkIBegbIB2giQB1gfBuAFIGEAOIgEAKIgIATQgUAognAhQgKAIgSALIgRALIgMALIgrAsIhyB2QhOBSh7A3Qh1A1ikAhQh6AXh2AJIiiAJQgiABgQAdIglA/IAAABQgzBXgYAsQgzBagXBFIgFASIAPgDIA7gRIABAAQBfgcApgNQBAgVB6gWIABAAIAxgKQBzgWBuABQCUACCPBHQAfAPAtAYIABAAIAzAbQAIAFAAAJQgBALAGAHQAGAIAIAAIgGgPIACgCIABABIABAAIACACQBRBIAlA+IAUAoIAJAUIABADIAAAHQgDAOAAASIABANIAAAAIgBACQgEAhgTBBQgaBYgTAqQgPAjgSAKQgJAFgOACIgZAAIg4gBQgbgBgLgFQgTgKgNgZQgNgbgIg5QgJg7gMgaQgRglglgXQgkgXgpgBQgpAAglAVIgBABIgFAAIl5A9QiwAzi7BdIhmA0IhxA6QhnAyhZAAIgIAAgAF+HHIAHAAIgMAAIAFAAg");
	this.shape_14.setTransform(168.5348,137.3714);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.lf(["#055DB0","#0D957C"],[0,1],-23,203.2,232.5,-96.3).s().p("AIoN4QgRgZgIgxIADiLQABgkgBgPQgCgdgHgWQgMghgagZIgCAHIAAAAIgBADIADgJIAQhSIAAgDIABgDIAAgCIAAgFIAAgCIAAgCIABgLIAAgEIAAgFIAAgEIAAgEIAAgFIhpAAQjQAFjDA5QiwAzi7BdIhmA0IhxA6QhsA0hcgCIgZgDQgIgBgCgCQgFgEABgJQAAgCgEgGIgCgEIgEAAIgEATQgigKgagcIgBgFIAAgBIgCgMIgKAJIgEgEIgOgNQgCgEABgIQABgHAAgDQgBgFgFgEIgIATIgSgZQgyhLgYhVQgfhwAuh8QAbhKBHhUIHso7QAIgJgEgNQgCgFADgIIgDgEIgFgJQgBgGADgHQAAgCgCgEIgCgEIgKAIIgBgEQgBgGABgBQAFgGgBgHQgBgFgEgHIAAgCIgLgRIgGgKQgMgUAGgVIAGgMIABAEQABAIACABQACADAGgFIAEAAIADACQAcAcAggCQAzgFAggeQAVgUAcgwIAIgMQAYgoAOgSQAfgoAwAAQAVAAAJANQABABADABIACABIABATIAEABIAHgNIAjAbQALAKAIAEQAXALANAAQBZADB7gkIBegbIB2giQB1gfBuAFIGEAOIgEAKIgIATQgUAognAhQgKAIgSALIgRALIgMALIgrAsIhyB2QhOBSh7A3Qh1A1ikAhQh6AXh2AJIiiAJQgiABgQAdIglA/IAAABQgzBXgYAsQgzBagXBFIgFASIAPgDIA7gRIABAAQBfgcApgNQBAgVB6gVIABAAIAxgKQBzgWBuABQCUACCPBGQAfAPAtAYIABAAIAzAbQAIAFAAAJQgBALAGAHQAGAIAIAAIgGgPIACgCIABABIABAAIACACQBRBIAlA+IAUAoIAJAUIABADIAAAGQgDAPAAASIAGBrQADBAgGAqQgKBHgxBYIgUAiQgfAegqAdQhdA+hQAAQgPAAgNgCg");
	this.shape_15.setTransform(168.5348,144.389);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.lf(["#055DB0","#0D957C"],[0,1],-23,185.5,232.5,-114).s().p("ACcQgQgFgHgBgRQgEhWANhUIAJg8QAGgiAAgaIAAgBQBxhlBOhiQBNhgAihZQAbhCgChUIhpAAQjQAFjDA5QiwAzi7BdIhmA0IhxA6QhsA0hcgCIgZgDQgIgBgCgCQgFgEABgJQAAgCgEgGIgCgEIgEAAIgEATQgigKgagcIgBgFIAAgBIgCgMIgKAJIgEgEIgOgNQgCgEABgIQABgHAAgDQgBgFgFgEIgIATIgSgZQgyhLgYhVQgfhwAuh8QAbhJBHhUIHso8QAIgJgEgNQgCgFADgIIgDgEIgFgJQgBgGADgHQAAgCgCgEIgCgEIgKAIIgBgEQgBgGABgBQAFgGgBgHQgBgFgEgHIAAgCIgLgRIgGgKQgMgUAGgVIAGgMIABAEQABAIACABQACADAGgFIAEAAIADACQAcAcAggCQAzgFAggeQAVgUAcgwIAIgMQAYgoAOgSQAfgoAwAAQAVAAAJANQABABADABIACABIABATIAEABIAHgNIAjAbQALAKAIAEQAXALANAAQBZADB7gkIBegbIB2giQB1gfBuAFIGEAOIgEAKIgIATQgUAognAhQgKAIgSALIgRALIgMALIgrAsIhyB2QhOBSh7A3Qh1A1ikAhQh6AXh2AJIiiAJQgiABgQAdIglA/IAAABQgzBXgYAsQgzBbgXBFIgFASIAPgDIA7gRIABAAQBfgcApgNQBAgVB6gWIABAAIAxgKQBzgWBuABQCUACCPBHQAfAPAtAYIABAAIAzAbQAIAFAAAJQgBALAGAHQAGAIAIAAIgGgPIACgCIABABIABAAIACACQBRBHAlA+IAUAoIAJAUIABADIAAAHQgDAOAAASIAGBrQADBAgGAqQgKBHgxBYIgZAsQgPAagJATQgFAMgfBVQgWA7gXAgIgOARIAEgFQg1AeghAXIhMA8QguAmghASQg4AehNAMQg5AJhUAAQgaAAgJgLg");
	this.shape_16.setTransform(168.5348,162.0658);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.lf(["#055DB0","#0D957C"],[0,1],-23,167.2,232.5,-132.2).s().p("AiHTdQgYgIgggeQgvgtglgpQgngqgJgfQgHgWADgiIAEg6IgBgTQDqiFDKiqQCbiBBih8QBNhgAihYQAbhDgChTIhpAAQjQAEjDA5QiwA0i7BdIhmA0IhxA5QhsA1hcgDIgZgCQgIgCgCgCQgFgEABgIQAAgDgEgGIgCgDIgEAAIgEATQgigLgagcIgBgEIAAgCIgCgLIgKAIIgEgEIgOgNQgCgDABgJQABgGAAgDQgBgFgFgFIgIAUIgSgaQgyhLgYhVQgfhvAuh8QAbhKBHhTIHso9QAIgJgEgNQgCgFADgHIgDgEIgFgKQgBgGADgGQAAgCgCgFIgCgEIgKAIIgBgDQgBgGABgCQAFgGgBgHQgBgEgEgIIAAgBIgLgRIgGgLQgMgTAGgVIAGgMIABAEQABAHACACQACACAGgFIAEAAIADADQAcAcAggDQAzgFAggeQAVgTAcgwIAIgMQAYgoAOgTQAfgoAwAAQAVAAAJANQABACADABIACAAIABAUIAEABIAHgNIAjAbQALAKAIAEQAXALANAAQBZACB7gjIBegbIB2giQB1ggBuAFIGEAOIgEAKIgIAUQgUAognAgQgKAJgSALIgRAKIgMALIgrAsIhyB2QhOBSh7A4Qh1A1ikAgQh6AYh2AJIiiAIQgiACgQAcIglBAIAAAAQgzBXgYAtQgzBagXBFIgFASIAPgCIA7gSIABAAQBfgbApgNQBAgVB6gXIABAAIAxgJQBzgXBuACQCUABCPBHQAfAPAtAZIABAAIAzAbQAIAFAAAJQgBALAGAHQAGAHAIAAIgGgPIACgBIABAAIABAAIACACQBRBJAlA+IAUAoIAJATIABADIAAAHQgDAOAAASIAGBqQADBBgGApQgKBIgxBYIgZAsQgPAagJASQgFAMgfBVQgWA7gXAhIgdAiQgSAVgJAOIgEAIIACgPQiRDdioC5Ig0AUIigA9IhCAZQglAMgeAEQggAFg1ABIgKAAQgZAAgPgEg");
	this.shape_17.setTransform(168.5348,180.3235);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.lf(["#055DB0","#0D957C"],[0,1],-23,154.6,232.5,-144.8).s().p("AnnVfQiTgGhxg3QgzgYgYgcQgOgQgOgbIgWguIgeg8QgRgkgGgcQgFgZACghIABgTIgHgBIASACQCMAKBxgnQCXg0ChhZQD5iJDWi0QCbiBBih8QBNhgAihYQAbhCgChTIhpAAQjQAEjDA5QiwAzi7BdIhmA0IhxA5QhsA1hcgDIgZgCQgIgCgCgCQgFgEABgIQAAgDgEgGIgCgDIgEAAIgEATQgigLgagcIgBgEIAAgCIgCgLIgKAIIgEgEIgOgNQgCgDABgJQABgGAAgDQgBgFgFgFIgIAUIgSgaQgyhLgYhUQgfhvAuh9QAbhKBHhTIHso9QAIgJgEgNQgCgFADgHIgDgEIgFgKQgBgGADgGQAAgCgCgFIgCgEIgKAIIgBgDQgBgGABgCQAFgGgBgHQgBgEgEgIIAAgBIgLgRIgGgLQgMgTAGgVIAGgMIABAEQABAHACACQACACAGgFIAEAAIADADQAcAcAggDQAzgFAggeQAVgTAcgwIAIgMQAYgoAOgTQAfgoAwAAQAVAAAJANQABACADABIACAAIABAUIAEABIAHgNIAjAbQALAKAIAEQAXALANAAQBZACB7gjIBegbIB2giQB1ggBuAFIGEAOIgEAKIgIAUQgUAognAgQgKAJgSALIgRAKIgMALIgrAsIhyB2QhOBSh7A4Qh1A1ikAgQh6AYh2AJIiiAIQgiACgQAcIglBAIAAAAQgzBXgYAtQgzBagXBFIgFASIAPgCIA7gSIABAAQBfgbApgNQBAgVB6gXIABAAIAxgJQBzgXBuACQCUABCPBHQAfAPAtAZIABAAIAzAbQAIAFAAAJQgBALAGAHQAGAHAIAAIgGgPIACgBIABAAIABAAIACACQBRBJAlA+IAUAoIAJATIABADIAAAHQgDAOAAATIAGBqQADBAgGApQgKBIgxBYIgZAsQgPAagJASQgFAMgfBVQgWA7gXAhIgdAiQgSAVgJAOIgEAIIACgPQiqECjJDSQh/CDh/BjIgPAFQhkAjiFAZQiCAXhrAAIgjAAg");
	this.shape_18.setTransform(168.5348,192.9224);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.lf(["#055DB0","#0D957C"],[0,1],-18.2,145,237.3,-154.5).s().p("AqaW+QhhgLhAgpQgUgNgXgZIgngtIgSgVIgBgBQgHgIAEgHIABgBIgEgOIgGAGIgBAAIgDADIgXgdIAVAJIgTgZIgBgBIgaghIAJgBIACAAIgOgYIgIAMIgYgiIgKAFIgBgDIAAgFQAEgIgEgMIgCgGQgThCgChAIgCgJIgRAGQgKACgDgDQgCgDAAgIIgBgGIAGABQAFACAFAAQAPgBACgEQADgHgDgPIgEgOIgFgNQgCgLAKABIAGgCQAAAAABgBQAAAAABgBQAAAAAAgBQAAAAAAAAQAQgtAEgtQgIAFgDAIQgDAJgDAcQgDABgFgDQgFgCgCAAQgEAAgDAHQgCgmAHgWQAUgyASggQASgiAegxIAfg1QAGgKAFgPIADgGIAAgBIABgBQADgLAIADQACABABAEIABAIIgUCTQgGAvAAAZQgBA/A6ANQAKADAOABQCNAKBxgnQCWg0CihZQD4iJDWi0QCbiBBih8QBNhgAjhXQAbhDgDhTIhoAAQjRAEjEA5QivA0i7BcIhmA0IhxA5QhsA1hcgDIgYgCQgJgCgCgCQgEgEAAgIQABgDgEgGIgDgDIgEAAIgEATQghgLgbgcIgBgEIAAgCIgCgLIgKAIIgEgEIgOgNQgCgDABgJQACgGgBgDQgBgFgEgFIgIAUIgSgaQgzhKgXhVQgghvAuh9QAbhKBHhTIHso9QAIgJgEgNQgBgFACgHIgDgEIgEgKQgCgGADgGQAAgCgCgFIgCgEIgKAIIgBgDQAAgGAAgCQAFgGAAgHQgCgEgDgIIgBgBIgKgRIgHgLQgLgTAFgVIAGgMIABAEQABAHACACQACACAGgFIAEAAIADADQAcAcAggDQA0gFAfgeQAVgTAdgwIAHgMQAYgoAOgTQAfgoAwAAQAVAAAJANQABACADABIACAAIACAUIADABIAHgNIAiAbQALAKAIAEQAXALAPAAQBYACB7gjIBegbIB2giQB2ggBtAFIGEAOIgDAKIgIAUQgVAognAgQgKAJgSALIgRAKIgMALIgrAsIhxB2QhPBSh7A4Qh1A1ikAgQh5AYh3AJIiiAIQgiACgQAcIglBAIAAAAQgzBXgYAtQgzBagXBFIgEASIAOgCIA8gSIAAAAQBfgbApgNQBAgVB6gXIABAAIAxgJQBzgXBuACQCUABCQBHQAfAPAsAZIABAAIA0AbQAHAFAAAJQgBALAGAHQAGAHAJAAIgHgPIACgBIABAAIABAAIADACQBQBJAlA+IAUAoIAJATIABADIAAAHQgCAOAAATIAFBqQADBBgGApQgJBHgyBYIgZAsQgPAagJASQgFAMgfBVQgVA7gYAhIgdAiQgRAVgKAOIgEAIIACgPQipECjKDSQjMDTjMB/Qi6B0iyAnQhXAUhQAAQgfAAgfgDg");
	this.shape_19.setTransform(163.7,202.6479);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_6}]},9).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_9}]},1).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_11}]},1).to({state:[{t:this.shape_12}]},1).to({state:[{t:this.shape_13}]},1).to({state:[{t:this.shape_14}]},1).to({state:[{t:this.shape_15}]},1).to({state:[{t:this.shape_16}]},1).to({state:[{t:this.shape_17}]},1).to({state:[{t:this.shape_18}]},1).to({state:[{t:this.shape_19}]},1).wait(66));

	// 레이어_13 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_43 = new cjs.Graphics().p("ACoE7IAAkJMAmcAAAIAAEJg");
	var mask_graphics_44 = new cjs.Graphics().p("ACoGKIAAmmMAmcAAAIAAGmg");
	var mask_graphics_45 = new cjs.Graphics().p("ACoHZIAApFMAmcAAAIAAJFg");
	var mask_graphics_46 = new cjs.Graphics().p("ACoIoIAArjMAmcAAAIAALjg");
	var mask_graphics_47 = new cjs.Graphics().p("ACoJ3IAAuBMAmcAAAIAAOBg");
	var mask_graphics_48 = new cjs.Graphics().p("ACoLHIAAwgMAmcAAAIAAQgg");
	var mask_graphics_49 = new cjs.Graphics().p("ACoMWIAAy+MAmcAAAIAAS+g");
	var mask_graphics_50 = new cjs.Graphics().p("ACoNlIAA1dMAmcAAAIAAVdg");
	var mask_graphics_51 = new cjs.Graphics().p("ACoO0IAA37MAmcAAAIAAX7g");
	var mask_graphics_52 = new cjs.Graphics().p("ACoQDIAA6ZMAmcAAAIAAaZg");
	var mask_graphics_53 = new cjs.Graphics().p("ACoRTIAA84MAmcAAAIAAc4g");
	var mask_graphics_54 = new cjs.Graphics().p("ACoSiIAA/WMAmcAAAIAAfWg");
	var mask_graphics_55 = new cjs.Graphics().p("ACoTxMAAAgh0MAmcAAAMAAAAh0g");
	var mask_graphics_56 = new cjs.Graphics().p("ACoVAMAAAgkTMAmcAAAMAAAAkTg");
	var mask_graphics_57 = new cjs.Graphics().p("ACoWPMAAAgmxMAmcAAAMAAAAmxg");
	var mask_graphics_58 = new cjs.Graphics().p("ACoXfMAAAgpQMAmcAAAMAAAApQg");
	var mask_graphics_59 = new cjs.Graphics().p("ACoYuMAAAgruMAmcAAAMAAAArug");
	var mask_graphics_60 = new cjs.Graphics().p("ACoZ9MAAAguMMAmcAAAMAAAAuMg");
	var mask_graphics_61 = new cjs.Graphics().p("ACobMMAAAgwrMAmcAAAMAAAAwrg");
	var mask_graphics_62 = new cjs.Graphics().p("ACocbMAAAgzJMAmcAAAMAAAAzJg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(43).to({graphics:mask_graphics_43,x:262.75,y:31.475}).wait(1).to({graphics:mask_graphics_44,x:262.75,y:39.3934}).wait(1).to({graphics:mask_graphics_45,x:262.75,y:47.3118}).wait(1).to({graphics:mask_graphics_46,x:262.75,y:55.2302}).wait(1).to({graphics:mask_graphics_47,x:262.75,y:63.1487}).wait(1).to({graphics:mask_graphics_48,x:262.75,y:71.0671}).wait(1).to({graphics:mask_graphics_49,x:262.75,y:78.9855}).wait(1).to({graphics:mask_graphics_50,x:262.75,y:86.9039}).wait(1).to({graphics:mask_graphics_51,x:262.75,y:94.8223}).wait(1).to({graphics:mask_graphics_52,x:262.75,y:102.7407}).wait(1).to({graphics:mask_graphics_53,x:262.75,y:110.6591}).wait(1).to({graphics:mask_graphics_54,x:262.75,y:118.5776}).wait(1).to({graphics:mask_graphics_55,x:262.75,y:126.496}).wait(1).to({graphics:mask_graphics_56,x:262.75,y:134.4144}).wait(1).to({graphics:mask_graphics_57,x:262.75,y:142.3328}).wait(1).to({graphics:mask_graphics_58,x:262.75,y:150.2512}).wait(1).to({graphics:mask_graphics_59,x:262.75,y:158.1696}).wait(1).to({graphics:mask_graphics_60,x:262.75,y:166.088}).wait(1).to({graphics:mask_graphics_61,x:262.75,y:174.0064}).wait(1).to({graphics:mask_graphics_62,x:262.75,y:181.9249}).wait(26));

	// 레이어_11
	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AkJWPQhUgBALhdQAHhDAKgpQAMg6AWgtQAIgRARgXQAPgVAHgMQAKgUACgSQADgegThHIgFgXQgNg1gJgaQgQgsgXgcQgHgIgUgRQgbgYgJgNQgPgXAKgYQALgaAhgLQATgGAwgEQBAgFAXgNQAngWgGg6QgIhThDg0Qg1gqhZgUQgggIg6gVQgygTgYgGQgZgHgvgFQgtgFgTgEQgjgIgXgPQg4gkAKgzQAGgfAqg+QAPgVAKgRIAegvQAthDAOgjQAXg8gVguQgQgjgigPQgUgJgvgIQgfgFgRgEQgagIgUgMQhDgtAAggQAAgVAcgYQARgOAzghIAQgJIAAABQApgaCDhOQDDhyBehCQATgOARgWQAMgOASgcQAVgfALgOQAUgYAVgNQAegTAWAJQANAGAXAaQAPASANALQAZAVAnAGQAXADAxgCIAigBIAoACQAyAEAOgGQAXgJgVgnQgEgJgRgWQgXgggCgPQgCgJAEgKQAGgOATgOQATgNAfgGQAUgDAogDQAsgDASgEIAFgBQA7gOAPgQQAGgHACgKQABgFABgLQABgTAFgJQAMgYAbgMQAQgHAkgHIAagFQAqgKAPgSQAMgPAKguIABgFQAGgdAHgSQBqA8ApAtQApAsAPASQgxAQgNAKQgeAagjAvQgdAngZAqQgaAtgJA0QgFAfgCBAQgCAygDAZQgGA7giAjQgeAeg6ASQgrANgdAWQgSANghAlQgTAWgOAOQgZAagpAZQgZAPg2AbQhXAsgjAcQg8AvgOA/QgOA+AoAuQAYAbBFAqQApAZARANQApAfAbAiIAPAUQA5BOApAsIANAPQBRBYAnAyQBBBVAYBGQALAeADApQACAYgBAyIAAAdQABAxAEAbQgiAhg5BPQg7BRgfAfIiRCbQhRBWhAA2QhEA5hBAlIiIBIQgLAGhBALQg/ALgNAAg");
	this.shape_20.setTransform(401.075,205.575);
	this.shape_20._off = true;

	var maskedShapeInstanceList = [this.shape_20];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.shape_20).wait(43).to({_off:false},0).wait(45));

	// 레이어_10
	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.lf(["#055DB0","#0D957C"],[0,1],-300,268.9,-44.5,-30.6).s().p("AksERQhOgGg8gUQglgNgRgSQgOgPgNgjQgqh2AGh6IAAgXIASgKQANgIAIAJQABACAIgCQAIgCAAgCQABgGAEgDQADgBAHgBIACgBQAMgCAFgLQAJgUAVgPQANgKAbgNQA4gbBGgSQA4gPBNgMIBCgIQBQgLBbAuQAeAPBtBRICGBmIBAA1IBIA/QAQAOAUAmIAJATQAEAGgDAHQgCAGgIAEIgbARIAGgEQgLgDgLAAQgYgCgfAJQgKADgrAPIhbAfIgIADIgPgBQg5gChWANIiOAVQgzAFhnABIgnAAQhBAAgmgDg");
	this.shape_21.setTransform(445.59,78.6627);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.lf(["#055DB0","#0D957C"],[0,1],-281.3,252.3,-25.8,-47.1).s().p("AnsGyQg5gKgrgYQg7gignhAQgkg7gMhJQgPhcAZh/IgEADIgHAEIAMgIIAigWIACgBQAZgPA9gfQA1gcAcgQQAsgaAhgaQAVgRAwgZIAcgPQANgIAIAJQABABAIgCQAIgCAAgBQABgHAEgCQADgCAHgBIACAAQAMgCAFgMQAJgTAVgPQANgKAbgOQA4gaBGgTQA4gOBMgNIBCgIQBRgKBbAtQAeAQBtBRICGBlIBAA3IBIA+QAQAPAUAmIAJASQAEAHgDAGQgCAGgIAEIgbAQIAGgEQgLgCgLgBQgYgBgfAJQgKACgrAQIhbAfQg0ATgiAUQgwAchCBDQhMBOghAZIgaASQgWAAgbALQgOAGgVAMIgjAUQgkASgwAMQghAHg5AIQiZAVhfABIgHAAQg5AAgrgIg");
	this.shape_22.setTransform(426.8651,95.228);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.lf(["#055DB0","#0D957C"],[0,1],-261.8,234.2,-6.3,-65.2).s().p("ArkJvQgmgCgcgLQgcgLgwgkQgbgVgKgPQgQgXgDgxQgEhRAShoQAIgrAgiNIAHgjIAKgIIBThIQAhgdBVhDQA/gxAcgYQAhgcAvgcQAZgPA8gfQA2gcAcgQQAsgaAggaQAWgRAvgZIAcgPQANgIAJAJQABABAIgCQAHgCABgBQAAgHAFgCQACgCAHgBIACAAQANgCAFgMQAJgTAUgPQAOgKAbgOQA3gaBGgTQA3gOBOgNIBCgIQBRgKBbAtQAeAQBsBRICGBlIBAA3IBJA+QAPAPAUAmIAKASQADAHgCAGQgDAHgHAEIgcAQIAGgEQgKgCgMgBQgYgBgeAJQgKACgrAQIhbAfQg1ATgiAUQgvAchCBCQhNBOggAZIggAWQgSAOgMALQgUAUgSAfIgMAXQgSAEgSAMQgPAKgXAVQhjBdhDAtQiJBdjEAtQiPAhjeAQQghADgXAAIgMAAg");
	this.shape_23.setTransform(407.3407,113.3377);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.lf(["#055DB0","#0D957C"],[0,1],-247,221,8.5,-78.4).s().p("AutLuQg7gQgqhYQg9iCAXhyQALgrADgWQAFgggIgXIAHgHIAkglQAZgcAjg0QAshAAdgbQA4g1B2hmIBThJQAhgdBVhDQA/gxAcgYQAhgcAvgcQAZgPA8gfQA2gcAcgQQAsgaAggaQAWgRAvgZIAcgPQAMgIAJAJQABABAIgCQAHgCABgBQAAgHAFgCQACgCAHgBIACAAQANgCAFgMQAJgTAUgPQAOgKAbgOQA4gaBGgTQA3gOBOgNIBCgIQBRgKBbAtQAeAQBsBRICGBlIBAA3IBJA+QAPAPAUAmIAKASQADAHgCAGQgDAHgHAEIgcAQIAGgEQgKgCgMgBQgYgBgeAJQgKACgrAQIhbAfQg1ATgiAUQgvAchCBDQhNBOggAZIggAVQgSAOgMALQgUAUgSAfQgLAUgRAmQghARgcAYQgoAjgZAtQgKASgNAeIgVAwQglBLhZBbIgsAuIgBACIgCACIgMAQIAGgJIACgCQgUgCgXAJQgOAGgbAQQhIAqgxAZQhOApgzAKQgkAIhDABInwAKQgqAAgRgFg");
	this.shape_24.setTransform(392.5489,126.5266);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.lf(["#055DB0","#0D957C"],[0,1],-231.4,194.7,24.1,-104.8).s().p("AwVPzQgxgLgggaQg5gwgJhyIgFhZQgEg1gLgjQgCgJgPgkQgKgcgEgSIAAgCIBujTIADgFIAFgHQASgVARgcIAagzQAbg4AXgfQAggpBMhQIAkgkQAZgbAjg0QAshBAdgbQA4g1B2hnIBThJQAhgdBVhDQA/gxAcgYQAhgcAvgbQAZgPA8ggQA2gbAcgQQArgaAggaQAWgSAvgZIAcgPQANgIAJAJQABACAIgCQAHgCABgCQAAgGAFgDQACgBAHgBIACgBQANgCAFgLQAJgUAUgPQAOgKAbgNQA4gbBGgSQA3gPBOgMIBCgIQBRgLBbAuQAeAPBsBRICGBmIBAA2IBJA/QAPAOAUAmIAKATQADAGgCAHQgDAGgHAEIgcARIAGgEQgKgDgMAAQgYgCgeAJQgKADgrAPIhbAfQg1ATgiAVQgvAchCBDQhNBOggAYIggAXQgSANgMAMQgUAUgSAfQgLAUgRAmQghAQgcAZQgoAjgZAsQgKARgNAfIgVAwQglBKhZBbIgsAvQgXAbgKAaQgKAYgEAlIAAAEIgBAKIAAgFIABgIQgOALgNAQQgLANgYAkIgKAPQgQgDgQAEQgoAKgkArQgJALgUAbQgSAYgLANQgoAthVAxQhtA+gbAUIgnAgQgYAUgQALQgrAdhHAYQjTBIjbACIgGAAQgyAAgigHg");
	this.shape_25.setTransform(376.9146,152.8531);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.lf(["#055DB0","#0D957C"],[0,1],-222.4,176.5,33.1,-123).s().p("AuXSqQglgKgxgqQg7gzgXgMQgMgGgngPQghgNgRgLQgdgYgPgKQgbgRgWAEQgJgQgRhMQgJgngRgWIACgUQAGg6AVhEQAQgwAehKIANgfIDJmCIADgFIAGgHQASgVAQgcIAbgzQAag3AYgfQAfgpBNhQIAjglQAagbAig0QAshBAdgbQA5g1B2hnIBThJQAggdBVhDQA/gxAcgYQAhgcAvgbQAZgPA9ggQA0gbAcgQQAsgaAhgaQAVgSAwgZIAcgPQANgIAIAJQABACAIgCQAIgCAAgCQABgGAEgDQADgBAHgBIACgBQAMgCAFgLQAJgUAVgPQANgKAbgNQA4gbBGgSQA4gPBNgMIBCgIQBRgLBbAuQAeAPBtBRICGBmIBAA2IBIA/QAQAOAUAmIAJATQAEAGgDAHQgCAGgIAEIgbARIAGgEQgKgDgMAAQgYgCgfAJQgKADgrAPIhbAfQg0ATgiAVQgwAchCBDQhMBOghAYIgfAXQgTANgLAMQgVAUgRAfQgMAUgRAmQggAQgdAZQgoAjgYAtQgKARgNAfIgWAwQgkBKhZBaIgsAvQgYAbgKAaQgJAYgEAlIgBAEIgBAKIABgFIABgIQgOALgOAQQgLANgYAkQgWAggOAQIgbAaQgRARgJALQgQAVgNAfQgHARgMAnQgTBDgGAmQgbA4gNAfQgOAjgKAfIgkAcQhBA4haA0QhAAmhnAzQjlByijAxQgpANgcADQgNACgMAAQgXAAgUgGg");
	this.shape_26.setTransform(367.9521,171.0545);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.lf(["#055DB0","#0D957C"],[0,1],-221.8,162.7,33.7,-136.7).s().p("AtlU6QhrgChqgkQhcgegkgyIgQgbQgKgQgKgIQgSgRgcAAQgZhYgNhhQgOhtAIh2QAEgKADgMQACgKADgfQAGg7AVhDQAPgxAehJIANgfIDKmCIADgGIAFgGQASgVARgcIAagyQAbg4AXgfQAggpBMhQIAkglQAZgcAjg0QAshAAdgbQA4g1B2hnIBThJQAhgdBVhDQA/gxAcgYQAhgcAvgcQAZgPA8gfQA1gcAcgQQAsgaAggaQAWgRAvgZIAcgPQANgIAJAJQABABAIgCQAHgCABgBQAAgHAFgCQACgCAHgBIACAAQANgCAFgMQAJgTAUgPQAOgKAbgOQA4gaBGgTQA3gOBOgNIBCgIQBRgKBbAtQAeAQBsBRICGBlIBAA3IBJA+QAPAPAUAmIAKASQADAHgCAGQgDAHgHAEIgcAQIAGgEQgKgCgMgBQgYgBgeAJQgKACgrAQIhbAfQg1ATgiAUQgvAchCBDQhNBOggAZIggAWQgSAOgMALQgUAUgSAfQgLAUgRAmQghARgcAYQgoAjgZAtQgKASgNAeIgVAwQglBLhZBbIgsAuQgXAbgKAaQgKAXgEAlIAAAEIgBAKIAAgEIABgJQgOALgNAQQgLAOgYAjQgWAggPAQIgbAbQgRAQgJAMQgQAUgMAfQgHARgMAnQgUBDgFAmQgcA4gMAgQgYA3gLAwQgSAKgOAWQgJAPgLAeIgCAFIgIAVIAFgMIABgEIgmAiQjACpimDDQguA3gbAUQglAeg6AUQheAihrAAIgMAAg");
	this.shape_27.setTransform(367.32,184.8319);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.lf(["#055DB0","#0D957C"],[0,1],-221.8,149.9,33.7,-149.6).s().p("ApgW5QiWgHiHgRQhFgHgkgNQgwgTgZgGIgUgEIgPgRQgRgUgPgVIgCgCIgCgCQiXjOglkdQgOhuAIh1QAEgKADgMQACgKADggQAGg6AVhEQAPgwAehKIANgfIDKmBIADgFIAFgHQASgVARgcIAagzQAbg4AXgfQAggpBMhQIAkglQAZgbAjg0QAshBAdgbQA4g1B2hnIBThJQAhgdBVhDQA/gxAcgYQAhgcAvgbQAZgPA8ggQA1gbAcgQQAsgaAggaQAWgSAvgZIAcgPQANgIAJAJQABACAIgCQAHgCABgCQAAgGAFgDQACgBAHgBIACgBQANgCAFgLQAJgUAUgPQAOgKAbgNQA4gbBGgSQA3gPBOgMIBCgIQBRgLBbAuQAeAPBsBRICGBmIBAA2IBJA/QAPAOAUAmIAKATQADAGgCAHQgDAGgHAEIgcARIAGgEQgKgDgMAAQgYgCgeAJQgKADgrAPIhbAfQg1ATgiAVQgvAchCBDQhNBOggAYIggAXQgSANgMAMQgUAUgSAfQgLAUgRAmQghAQgcAZQgoAjgZAtQgKARgNAfIgVAwQglBKhZBbIgsAvQgXAbgKAaQgKAYgEAlIAAAEIgBAKIAAgFIABgIQgOALgNAPQgLANgYAkQgWAggPAQIgbAaQgRARgJALQgQAVgMAfQgHARgMAnQgUBCgFAnQgcA4gMAfQgYA4gLAwQgSAJgOAWQgJAQgLAdQgrB2gLBDQgFAggHBWQgFBNgHAuQgKBCgVA0QgQAsgnA/QgdAugYAdQghAmgjAVQgvAbhCAIQgeAEgoAAIg0gBg");
	this.shape_28.setTransform(367.32,197.666);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.lf(["#055DB0","#0D957C"],[0,1],-221.8,140.1,33.7,-159.3).s().p("AnMYcQgZgCg6gGIgCAAQirgUh6g5Qi4hVh4iiQiXjOglkdQgOhuAIh2QAEgJADgMQACgKADggQAGg6AVhEQAPgxAehJIANgfIDKmBIADgFIAFgHQASgWARgbIAagzQAbg4AXgfQAggpBMhQIAkglQAZgbAjg0QAshBAdgbQA4g1B2hnIBThJQAhgdBVhDQA/gxAcgYQAhgcAvgbQAZgPA8ggQA1gbAcgQQAsgaAggaQAWgSAvgZIAcgPQANgIAJAJQABACAIgCQAHgCABgCQAAgGAFgDQACgBAHgBIACgBQANgCAFgLQAJgUAUgPQAOgKAbgNQA4gbBGgSQA3gPBOgMIBCgJQBRgKBbAuQAeAPBsBRICGBmIBAA2IBJA/QAPAOAUAmIAKATQADAGgCAHQgDAGgHAEIgcARIAGgEQgKgDgMAAQgYgCgeAJQgKADgrAPIhbAfQg1ATgiAVQgvAchCBDQhNBOggAYIggAXQgSANgMAMQgUAUgSAeQgLAVgRAmQghAQgcAYQgoAkgZAtQgKARgNAfIgVAwQglBKhZBbIgsAvQgXAbgKAaQgKAYgEAlIAAAEIgBAKIAAgFIABgIQgOALgNAQQgLANgYAkQgWAggPAPIgbAaQgRARgJALQgQAVgMAfQgHARgMAnQgUBCgFAnQgcA3gMAgQgbA/gLA1QgHAigDAsQgCAWgCA4QgBAkACATQADAfANAUQAJAQAaAcQAPAUAMAcQAnBRAKBxQAHBGgDCFQAAAkgDATQgEAegKAVQgKAVgWAYIglAoIgrA4QgUAZgSAQQg5APg4AEQgfADg0gDIgXgBQgGgBgLgFIgJgDIgCABQgBARgNAIQgJAGgUACQgWACgaAAIgiAAg");
	this.shape_29.setTransform(367.32,207.4996);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.lf(["#055DB0","#0D957C"],[0,1],-221.8,140.1,33.7,-159.3).s().p("AnMYcQgZgCg6gGIgCAAQirgUh6g5Qi4hVh4iiQiXjOglkdQgOhuAIh2QAEgJADgMQACgKADggQAGg6AVhEQAPgxAehJIANgfIDKmBIADgFIAFgHQASgWARgbIAagzQAbg4AXgfQAggpBMhQIAkglQAZgbAjg0QAshBAdgbQA4g1B2hnIBThJQAhgdBVhDQA/gxAcgYQAhgcAvgbQAZgPA8ggQA1gbAcgQQAsgaAggaQAWgSAvgZIAcgPQANgIAJAJQABACAIgCQAHgCABgCQAAgGAFgDQACgBAHgBIACgBQANgCAFgLQAJgUAUgPQAOgKAbgNQA4gbBGgSQA3gPBOgMIBCgJQBRgKBbAuQAeAPBsBRICGBmIBAA2IBJA/QAPAOAUAmIAKATQADAGgCAHQgDAGgHAEIgcARIAGgEQgKgDgMAAQgYgCgeAJQgKADgrAPIhbAfQg1ATgiAVQgvAchCBDQhNBOggAYIggAXQgSANgMAMQgUAUgSAeQgLAVgRAmQghAQgcAYQgoAkgZAtQgKARgNAfIgVAwQglBKhZBbIgsAvQgXAbgKAaQgKAYgEAlIAAAEIgBAKIAAgFIABgIQgOALgNAQQgLANgYAkQgWAggPAPIgbAaQgRARgJALQgQAVgMAfQgHARgMAnQgWBKgEAoQgEAwASAYQATAZAqAHQAYADAzACQBLAIBXBAQA7AsAVArQANAcAFAmQADAXABAuQADCdgBAdQgCBpgVBMQgMAughBUIgKAZIjACpIAGgJQhUBIgGADQhOAnhCAVQhQAahNAGQgfADg0gDIgXgBQgGgBgLgFIgJgDIgCABQgBARgNAIQgJAGgUACQgWACgaAAIgiAAg");
	this.shape_30.setTransform(367.32,207.4996);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.lf(["#055DB0","#0D957C"],[0,1],-221.8,140.1,33.7,-159.3).s().p("AnMYcQgZgCg6gGIgCAAQirgUh6g5Qi4hVh4iiQiXjOglkdQgOhuAIh2QAEgJADgMQACgKADggQAGg6AVhEQAPgxAehJIANgfIDKmBIADgFIAFgHQASgWARgbIAagzQAbg4AXgfQAggpBMhQIAkglQAZgbAjg0QAshBAdgbQA4g1B2hnIBThJQAhgdBVhDQA/gxAcgYQAhgcAvgbQAZgPA8ggQA1gbAcgQQAsgaAggaQAWgSAvgZIAcgPQANgIAJAJQABACAIgCQAHgCABgCQAAgGAFgDQACgBAHgBIACgBQANgCAFgLQAJgUAUgPQAOgKAbgNQA4gbBGgSQA3gPBOgMIBCgJQBRgKBbAuQAeAPBsBRICGBmIBAA2IBJA/QAPAOAUAmIAKATQADAGgCAHQgDAGgHAEIgcARIAGgEQgKgDgMAAQgYgCgeAJQgKADgrAPIhbAfQg1ATgiAVQgvAchCBDQhNBOggAYIggAXQgSANgMAMQgUAUgSAeQgLAVgRAmQghAQgcAYQgoAkgZAtQgKARgNAfIgVAwQglBKhZBbIgsAvQgXAbgKAaQgKAYgEAlIgHA+IgKA3QgEAhAHAXQAKAiAjAXQAfATApAGQAcADAwgCQA2gCAWACQBSAFBIAxQBHAwAjBKQAOAcAVBHQATBBAAAkQABAegLAzIgfCgQgFAbgBAQQgBAXAIASIAAABIpgIYIAGgJQhUBIgGADQhOAnhCAVQhQAahNAGQgfADg0gDIgXgBQgGgBgLgFIgJgDIgCABQgBARgNAIQgJAGgUACQgWACgaAAIgiAAg");
	this.shape_31.setTransform(367.32,207.4996);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.lf(["#055DB0","#0D957C"],[0,1],-221.8,140.1,33.7,-159.3).s().p("AnMYcQgZgCg6gGIgCAAQirgUh6g5Qi4hVh4iiQiXjOglkdQgOhuAIh2QAEgJADgMQACgKADggQAGg6AVhEQAPgxAehJIANgfIDKmBIADgFIAFgHQASgWARgbIAagzQAbg4AXgfQAggpBMhQIAkglQAZgbAjg0QAshBAdgbQA4g1B2hnIBThJQAhgdBVhDQA/gxAcgYQAhgcAvgbQAZgPA8ggQA1gbAcgQQAsgaAggaQAWgSAvgZIAcgPQANgIAJAJQABACAIgCQAHgCABgCQAAgGAFgDQACgBAHgBIACgBQANgCAFgLQAJgUAUgPQAOgKAbgNQA4gbBGgSQA3gPBOgMIBCgJQBRgKBbAuQAeAPBsBRICGBmIBAA2IBJA/QAPAOAUAmIAKATQADAGgCAHQgDAGgHAEIgcARIAGgEQgKgDgMAAQgYgCgeAJQgKADgrAPIhbAfQg1ATgiAVQgvAchCBDQhNBOggAYIggAXQgSANgMAMQgUAUgSAeQgLAVgRAmQgRAkgGAUQgLAfgBAbQAAALABAMQguBFgkBnQgSA2ANAcQAOAbAjAJQAUAHAqAAIBHAAQAMAAAGACQAIACAOALIAgAXIAAAAIAVAlIgBAfQgCA7AGAiQAIAxAaAgQAJALAUAUQASATAFAQQADAJACARIADAaQAHAhAiAdQAWASArAWIgIAxQgWB/g2CVQgdBPgyB1IqUJGIAGgJQhUBIgGADQhOAnhCAVQhQAahNAGQgfADg0gDIgXgBQgGgBgLgFIgJgDIgCABQgBARgNAIQgJAGgUACQgWACgaAAIgiAAg");
	this.shape_32.setTransform(367.32,207.4996);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.lf(["#055DB0","#0D957C"],[0,1],-222.9,140.1,32.6,-159.3).s().p("AnXYcQgZgCg6gGIgCAAQirgUh6g5Qi4hVh4iiQiXjOglkdQgOhuAIh2QAEgJADgMQACgKADggQAGg6AVhEQAPgxAehJIANgfIDKmBIACgFIAGgHQASgWARgbIAagzQAbg4AXgfQAggpBMhQIAkglQAZgbAjg0QAshBAdgbQA4g1B2hnIBThJQAhgdBVhDQA/gxAcgYQAhgcAvgbQAZgPA8ggQA1gbAcgQQAsgaAggaQAWgSAvgZIAcgPQANgIAJAJQABACAIgCQAHgCABgCQAAgGAFgDQACgBAHgBIACgBQANgCAFgLQAJgUAUgPQAOgKAbgNQA4gbBGgSQA3gPBOgMIBCgJQBRgKBbAuQAeAPBsBRICGBmIBAA2IBJA/QAPAOAUAmIAKATQADAGgCAHQgCAEgDACQgJAEgJAGIgPALIAAAAIgFACQgLgIgNgDQgUgGgTAHQgUAGgdAZIgxArIAEgFQgaACgXAMQgQAIgkAdIguAiQgbAVgRAPQgyAsgWAtQgQAjAEAbIABAGQgJAQgEAQQgJAdAIAdQAIAeAYAPQAVAOAqgBIAMgBQAHAIAJAFQAQAKAbABIARAAIgCgIQAFAUAMAPQAXAfAyASQAGAIAJAGQAOALAZAIIAqANQA8AVAoA+QAhAyALA/IAAAAQgDA1gLA8IgDARQgMA+ggB0IgrCgQgPA5gNAhQgNAfgkBAQgTAigoBUIhcB0IgyA/IscK+IAGgJQhUBIgGADQhOAnhCAVQhQAahNAGQgfADg0gDIgXgBQgGgBgLgFIgJgDIgCABQgBARgNAIQgJAGgUACQgWACgaAAIgiAAg");
	this.shape_33.setTransform(368.4429,207.4996);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.lf(["#055DB0","#0D957C"],[0,1],-232.7,140.1,22.8,-159.3).s().p("Ao5YcQgZgCg6gGIgCAAQirgUh6g5Qi4hVh4iiQiXjOglkdQgOhuAIh2QAEgJADgMQACgKADggQAGg6AVhEQAPgxAehJIANgfIDKmBIACgFIAGgHQASgWARgbIAagzQAbg4AXgfQAggpBMhQIAkglQAZgbAjg0QAshBAdgbQA4g1B2hnIBThJQAhgdBVhDQA/gxAcgYQAhgcAvgbQAZgPA8ggQA2gbAcgQQArgaAggaQAWgSAvgZIAcgPQANgIAJAJQABACAIgCQAHgCABgCQAAgGAFgDQACgBAHgBIACgBQANgCAFgLQAJgUAUgPQAOgKAbgNQA4gbBGgSQA3gPBOgMIBCgJQBRgKBbAuQAeAPBsBRICGBmIBAA2IBJA/QAPAOAUAmIAKATQADAGgCAHQgDAGgHAEIgcARIAAAAIgNAHIAfAXQCLBtA6C4QAzCegLDDQgGB4gVBKQgfBuhHCLQh2Doi3DyQgeAohCBSIgyA/IscK+IAGgJQhTBIgGADQhOAnhDAVQhQAahNAGQgfADg0gDIgXgBQgGgBgLgFIgJgDIgCABQgBARgNAIQgJAGgUACQgWACgaAAIgiAAg");
	this.shape_34.setTransform(378.2332,207.4996);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_21}]},25).to({state:[{t:this.shape_22}]},1).to({state:[{t:this.shape_23}]},1).to({state:[{t:this.shape_24}]},1).to({state:[{t:this.shape_25}]},1).to({state:[{t:this.shape_26}]},1).to({state:[{t:this.shape_26}]},1).to({state:[{t:this.shape_26}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_28}]},1).to({state:[{t:this.shape_29}]},1).to({state:[{t:this.shape_30}]},1).to({state:[{t:this.shape_31}]},1).to({state:[{t:this.shape_32}]},1).to({state:[{t:this.shape_33}]},1).to({state:[{t:this.shape_34}]},1).wait(48));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(369,276.1,260,87.89999999999998);
// library properties:
lib.properties = {
	id: '1895DA1A8E804E4896ACCD5AF99EF048',
	width: 630,
	height: 400,
	fps: 36,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['1895DA1A8E804E4896ACCD5AF99EF048'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;